.\" (c) 2014, Dell Software, Inc. All rights reserved.
.TH VAS-SET-SAMBA-PASSWORD 8
.SH NAME
vas-set-samba-password \- Sets the host password as used by a Samba server
.SH SYNOPSIS
.B vas-set-samba-password
.RI [\-p\  prefix ]
.RI [\-s\  config-file ]
.SH DESCRIPTION
The
.B vas-set-samba-password
script is intended to be invoked directly by
vasd(1)
when it updates the host computer's password in Active Directory.
.PP
The following entry in /etc/opt/quest/vas/vas.conf will ensure this:
.RS 3n
.nf
[vasd]
 password\-change\-script = /opt/quest/libexec/vas\-set\-samba\-password
.fi
.RE
.SS OPTIONS
.TP
.RI \-p\  prefix
Specifies the prefix used to find the location of the Samba
tools used for password updates.
.TP
.RI \-s\  config-file
Specifies the location of the smb.conf file used to control password updates.
.SH "SEE ALSO"
vastool(1),
smb.conf(5),
.I http://rc.quest.com/topics/vasidmap/
.SH AUTHORS
Dell Software, Inc.
