#!/bin/sh
# 
# This script should be run by vasd whenever it updates the machine secret
# (the host/ keytab). The original password should be bassed on standard
# input and terminated with a newline.
#
exec /opt/quest/bin/net -f -i changesecretpw
