#!/bin/sh
# 
# This script should be run by vasd whenever it updates the machine secret
# (the host/ keytab). The original password should be passed in on standard
# input and terminated with a newline.
#
read secretpw
OS=`uname -s`
if [ "$OS" = "AIX" ]; then
	SMBVER=`echo \`/opt/pware/samba/*/sbin/smbd --version\` | awk '{print $2}'`
fi

DOMAIN=`/opt/quest/bin/vastool -u host/ info domain | cut -d '.' -f 1 | tr '[a-z]' '[A-Z]'`
test -n "$DOMAIN" || exit -1

case ${OS} in
	HP-UX)	SAMBACONF=/etc/opt/samba/smb.conf
		TDBTOOL=/opt/samba/bin/tdbtool
		SECRETSTDB=/var/opt/samba/private/secrets.tdb
		$TDBTOOL $SECRETSTDB store SECRETS/MACHINE_PASSWORD/$DOMAIN "${secretpw}\0"
		$TDBTOOL $SECRETSTDB store SECRETS/MACHINE_SEC_CHANNEL_TYPE/$DOMAIN "\2\0\0\0"
		;;
	Linux)	SAMBACONF=/etc/samba/smb.conf
		TDBTOOL=/usr/bin/tdbtool
		SECRETSTDB=/etc/samba/secrets.tdb
		$TDBTOOL $SECRETSTDB store SECRETS/MACHINE_PASSWORD/$DOMAIN "${secretpw}\0"
		$TDBTOOL $SECRETSTDB store SECRETS/MACHINE_SEC_CHANNEL_TYPE/$DOMAIN "\2\0\0\0"
		;;
	SunOS)	SAMBACONF=/opt/csw/etc/samba/smb.conf
		NET=/opt/csw/bin/net
		echo ${secretpw} | ${NET} -f -i changesecretpw
		;;
	AIX)	SAMBACONF=/opt/pware/samba/${SMBVER}/smb.conf
		NET=/opt/pware/samba/${SMBVER}/bin/net
		echo ${secretpw} | ${NET} -f -i changesecretpw
		;;
	*)      SAMBACONF=/etc/samba/smb.conf
		exit -1
		;;
esac
