#!/bin/bash
# (c) 2006 Quest Software, Inc. All rights reserved.

# set shell separator to newline only, space is a valid char for us
IFS=$'\n'
VASPATH="/opt/quest/bin"
VASTMP="/var/tmp"


rm -f ${VASTMP}/idmap_new.tbl
touch ${VASTMP}/idmap_new.tbl

# For every user on AD
VASUSERS=`${VASPATH}/vastool list users | grep ":VAS:" | cut -d ':' -f 1,3`

for i in $VASUSERS
do
	# retrieve the Group Name
	USRNAME=`echo $i |cut -d ':' -f 1`
	# retrieve the group GID
	USRUID=`echo $i |cut -d ':' -f 2`
	# ask VASD to tell us the SID of this Group
	USRSID=`${VASPATH}/vasidmap -u -n "${USRNAME}"`
	echo "UID ${USRUID} ${USRSID}" >> ${VASTMP}/idmap_new.tbl
done

# For every group on AD
VASGROUPS=`${VASPATH}/vastool list groups | grep ":VAS:" | cut -d ':' -f 1,3`
for i in $VASGROUPS
do
	# retrieve the Group Name
	GRPNAME=`echo $i |cut -d ':' -f 1`
	# retrieve the group GID
	GRPGID=`echo $i |cut -d ':' -f 2`
	# ask VASD to tell us the SID of this Group
	GRPSID=`${VASPATH}/vasidmap -g -n "${GRPNAME}"`
	echo "GID ${GRPGID} ${GRPSID}" >> ${VASTMP}/idmap_new.tbl
done

grep -v "idmap backend" < /etc/opt/quest/samba/smb.conf > ${VASTMP}/vasidmap_smb.conf

# Load mappings into the tables
${VASPATH}/net -s ${VASTMP}/vasidmap_smb.conf idmap restore < ${VASTMP}/idmap_new.tbl >/dev/null 2>&1

# Delete old mappings
rm -f ${VASTMP}/idmap_dump.tbl
${VASPATH}/net -s ${VASTMP}/vasidmap_smb.conf idmap dump /var/opt/quest/lib/samba/winbindd_idmap.tdb > ${VASTMP}/idmap_dump.tbl

for i in `cat ${VASTMP}/idmap_dump.tbl |grep "S-"|cut -d ' ' -f 1,3`
do
	SIDTYPE=`echo $i | cut -d ' ' -f 1`
	SIDSTR=`echo $i | cut -d ' ' -f 2`
	if [ "${SIDTYPE}" = "UID" ]; then
		UNIXID=`${VASPATH}/vasidmap -s -U ${SIDSTR} 2>/dev/null`
	elif [ "${SIDTYPE}" = "GID" ]; then
		UNIXID=`${VASPATH}/vasidmap -s -G ${SIDSTR} 2>/dev/null`
	fi
	if [ "${UNIXID}" = "" ]; then
		${VASPATH}/net -s ${VASTMP}/vasidmap_smb.conf idmap delete /var/opt/quest/lib/samba/winbindd_idmap.tdb ${SIDSTR}
	fi
done

rm -f ${VASTMP}/idmap_new.tbl
rm -f ${VASTMP}/idmap_dump.tbl
rm -f ${VASTMP}/vasidmap_smb.conf
